// import 'dotenv/config';
import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
    index("routes/Home/index.tsx"),
    route(`privacy`, 'routes/Privacy/index.tsx'),
    route(`terms`, 'routes/Terms/index.tsx'),
    route(`dmca`, 'routes/DMCA/index.tsx'),
    route(`community-guidelines`, 'routes/CommunityGuidelines/index.tsx'),
    route(`brozystudio`, 'routes/studio/layout.tsx', [
        index('routes/studio/home/index.tsx'),
        route(`posts`, 'routes/studio/posts/index.tsx'),
        route(`post/:uniqueId`, 'routes/studio/post/$uniqueId/index.tsx'),
        route(`analytics`, 'routes/studio/analytics/index.tsx'),
        route(`comments`, 'routes/studio/comments/index.tsx'),
        route(`inspiration`, 'routes/studio/inspiration/index.tsx'),
    ]),
    route(`api`, 'routes/Api/layout.tsx', [
        route(`internal/client-error`, 'routes/Api/internal/client-error/index.tsx'),
        route(`internal/quota-check`, 'routes/Api/internal/quota-check/index.tsx'),
        route(`internal/quota-record`, 'routes/Api/internal/quota-record/index.tsx'),
        route(`internal/quota-purge`, 'routes/Api/internal/quota-purge/index.tsx'),
        route(`reports`, 'routes/Api/reports/index.tsx'),
        route(`feed-preferences`, 'routes/Api/feed-preferences/index.tsx'),
        route(`upload`, 'routes/Api/upload/index.tsx'),
        route(`upload/quota`, 'routes/Api/upload/quota/index.tsx'),
        route(`upload/profilepic`, 'routes/Api/upload/profilepic/index.tsx'),
        route(`upload/comment-image`, 'routes/Api/upload/comment-image/index.tsx'),
        route(`upload/thumbnail`, 'routes/Api/upload/thumbnail/index.tsx'),
        route(`captions/prepare`, 'routes/Api/captions/prepare/index.tsx'),
        route(`captions/load-prepare`, 'routes/Api/captions/load-prepare/index.tsx'),
        route(`internal/captions/consume-token`, 'routes/Api/internal/captions/consume-token/index.tsx'),
        route(`internal/captions/commit`, 'routes/Api/internal/captions/commit/index.tsx'),
        route(`internal/captions/uncommit`, 'routes/Api/internal/captions/uncommit/index.tsx'),
        route(`load/vtt/*`, 'routes/Api/load/vtt/index.tsx'),
        route(`upload-server-check`, 'routes/Api/upload-server-check/index.tsx'),
        route(`upload-job-status`, 'routes/Api/upload-job-status/index.tsx'),
        route(`webhooks/comment-image-storage`, 'routes/Api/webhooks/comment-image-storage/index.tsx'),
        route(`load/image/*`, 'routes/Api/load/image/index.tsx'),
        route(`load/profilepic/*`, 'routes/Api/load/profilepic/index.tsx'),
        // route(`get/*`, 'routes/Api/get/index.tsx'),
        route(`public-key`, 'routes/Api/PublicKey/index.tsx'),
        route(`handshake`, 'routes/Api/handshake/index.tsx'),
        // Per-session HMAC signing key  fetched once per tab, used by
        // signedFetch() to authenticate every other API call.
        route(`handshake/sig-key`, 'routes/Api/handshake/sig-key.tsx'),
        route(`email`, 'routes/Api/email/index.tsx'),
        route(`socials`, 'routes/Api/Socials/layout.tsx', [
            route(`info/*`, 'routes/Api/Socials/Info.tsx'),
            route(`*`, 'routes/Api/Socials/index.tsx'),
        ]),
        route(`video-processor`, 'routes/Api/videoProcessor/layout.tsx', [
            route(`status/:queueID`, 'routes/Api/videoProcessor/status.tsx'),
            route(`queue-status`, 'routes/Api/videoProcessor/queue-status.tsx'),
            index('routes/Api/videoProcessor/index.tsx'),
        ]),
        route(`likes`, 'routes/Api/likes/index.tsx'),
        route(`dislikes`, 'routes/Api/dislikes/index.tsx'),
        route(`interactions`, 'routes/Api/interactions/index.tsx'),
        route(`comments`, 'routes/Api/comments/index.tsx'),
        route(`comment-likes`, 'routes/Api/comment-likes/index.tsx'),
        route(`notifications`, 'routes/Api/notifications/index.tsx'),
        route(`push-vapid-public`, 'routes/Api/push-vapid-public/index.tsx'),
        route(`push-subscribe`, 'routes/Api/push-subscribe/index.tsx'),
        route(`gif-search`, 'routes/Api/gif-search/index.tsx'),
        route(`profile`, 'routes/Api/profile/index.tsx'),
        route(`settings`, 'routes/Api/settings/index.tsx'),
        route(`files`, 'routes/Api/files/index.tsx'),
        route(`files/thumbnails`, 'routes/Api/files/thumbnails.tsx'),
        route(`user-profile`, 'routes/Api/user-profile/index.tsx'),
        route(`user-files`, 'routes/Api/user-files/index.tsx'),
        route(`my-series`, 'routes/Api/my-series/index.tsx'),
        route(`series-episodes`, 'routes/Api/series-episodes/index.tsx'),
        route(`file-series`, 'routes/Api/file-series/index.tsx'),
        route(`profile-tab`, 'routes/Api/profile-tab/index.tsx'),
        route(`owner-videos`, 'routes/Api/owner-videos/index.tsx'),
        route(`related-videos`, 'routes/Api/related-videos/index.tsx'),
        route(`play-queue`, 'routes/Api/play-queue/index.tsx'),
        route(`play-queue/global`, 'routes/Api/play-queue/global/index.tsx'),
        route(`play/mint`, 'routes/Api/play/mint/index.tsx'),
        route(`studio/overview`, 'routes/Api/studio/overview/index.tsx'),
        route(`studio/posts`, 'routes/Api/studio/posts/index.tsx'),
        route(`studio/analytics`, 'routes/Api/studio/analytics/index.tsx'),
        route(`studio/comments`, 'routes/Api/studio/comments/index.tsx'),
        route(`studio/inspiration`, 'routes/Api/studio/inspiration/index.tsx'),
        route(`studio/post`, 'routes/Api/studio/post/index.tsx'),
        route(`studio/post/update`, 'routes/Api/studio/post/update/index.tsx'),
        route(`studio/post/delete`, 'routes/Api/studio/post/delete/index.tsx'),
        route(`studio/track`, 'routes/Api/studio/track/index.tsx'),
        route(`dynamic-series`, 'routes/Api/dynamic-series/index.tsx'),
        route(`download`, 'routes/Api/download/index.tsx'),
        route(`download/status`, 'routes/Api/download/status.tsx'),
        route(`download/cancel`, 'routes/Api/download/cancel.tsx'),
        route(`download/file/:fileId`, 'routes/Api/download/file.$fileId.tsx'),
        route(`recommendations`, 'routes/Api/recommendations/index.tsx'),
        route(`trending`, 'routes/Api/trending/index.tsx'),
        route(`feed`, 'routes/Api/feed/index.tsx'),
        route(`pip-feed`, 'routes/Api/pip-feed/index.tsx'),
        route(`feed/clear-history`, 'routes/Api/feed/clear-history/index.tsx'),
        route(`reel-feed`, 'routes/Api/reel-feed/index.tsx'),
        route(`content/:id`, 'routes/Api/content/$id/index.tsx'),
        route(`tag/:tagname`, 'routes/Api/tag.$tagname/index.tsx'),
        route(`playlist`, 'routes/Api/playlist/index.tsx'),
        route(`playlists`, 'routes/Api/playlists/index.tsx'),
        route(`playlists/contains`, 'routes/Api/playlists/contains.tsx'),
        route(`playlists/:id`, 'routes/Api/playlists/$id/index.tsx'),
        route(`search`, 'routes/Api/search/index.tsx'),
        route(`mentions`, 'routes/Api/mentions/index.tsx'),
        route(`tags`, 'routes/Api/tags/index.tsx'),
        route(`subscriptions`, 'routes/Api/subscriptions/index.tsx'),
        route(`adult-review`, 'routes/Api/adult-review/index.tsx'),
        route(`subscription-feed`, 'routes/Api/subscription-feed/index.tsx'),
        route(`mark-seen`, 'routes/Api/mark-seen/index.tsx'),
        route(`player-settings`, 'routes/Api/player-settings/index.tsx'),
        route(`views/increment`, 'routes/Api/views/increment.tsx'),
        route(`views/watch-history`, 'routes/Api/views/watch-history.tsx'),
        route(`views/watch-issue`, 'routes/Api/views/watch-issue.tsx'),
        route(`views/watch-time`, 'routes/Api/views/watch-time.tsx'),
        route(`saves`, 'routes/Api/saves/index.tsx'),
        route(`feed-signals`, 'routes/Api/feed-signals/index.tsx'),
        route(`personalization`, 'routes/Api/personalization/index.tsx'),
        route(`watch-progress`, 'routes/Api/watch-progress/index.tsx'),
        route(`series/resume`, 'routes/Api/series/resume.tsx'),
        route(`webauthn/register-options`, 'routes/Api/webauthn/register-options.tsx'),
        route(`webauthn/register-verify`, 'routes/Api/webauthn/register-verify.tsx'),
        route(`webauthn/login-options`, 'routes/Api/webauthn/login-options.tsx'),
        route(`webauthn/login-verify`, 'routes/Api/webauthn/login-verify.tsx'),
        route(`webauthn/credentials`, 'routes/Api/webauthn/credentials.tsx'),
        route(`auth/switch-account`, 'routes/Api/auth/switch-account.tsx'),
        route(`auth/remove-account`, 'routes/Api/auth/remove-account.tsx'),
        route(`server-env`, 'routes/Api/server-env/index.tsx'),
        route(`suggested-creators`, 'routes/Api/suggested-creators/index.tsx'),
        route(`sitemap`, 'routes/Api/sitemap/index.tsx'),
        route(`indexnow`, 'routes/Api/indexnow/index.tsx'),
    ]),
    route(`playlist`, 'routes/Playlist/index.tsx'),
    route(`playlist/:playlistId`, 'routes/Playlist/view.tsx'),
    route(`tag/:tagname`, 'routes/tag.$tagname.tsx'),
    route(`pip`, 'routes/pip/index.tsx'),
    route(`pip/:pipId`, 'routes/pip/$pipId.tsx'),
    route(`:id`, 'routes/Dynamic/layout.tsx', [
        index('routes/Dynamic/index.tsx'),
    ]),
    route(`search`, 'routes/Search/layout.tsx', [
        index('routes/Search/index.tsx'),
        route('*', 'routes/Search/Dynamic/index.tsx'),
    ]),
    route(`subscriptions`, 'routes/Subscriptions/index.tsx'),
    route(`features`, 'routes/Features/layout.tsx', [
        route(`incoming`, 'routes/Features/Incoming/index.tsx'),
    ]),
    route(`auth`, 'routes/Auth/layout.tsx', [
        route(`login`, 'routes/Auth/Login/index.tsx'),
        route(`signup`, 'routes/Auth/Signup/index.tsx'),
        route(`verify`, 'routes/Auth/Verify/index.tsx'),
        route(`reset`, 'routes/Auth/Reset/index.tsx'),
        route(`reset/confirm`, 'routes/Auth/Reset/confirm.tsx'),
    ]),
    route(`logout`, 'routes/Auth/Logout/index.tsx'),
    route(`settings`, 'routes/Settings/index.tsx'),
    route(`notifications`, 'routes/Notifications/index.tsx'),
    route(`profile/:username`, 'routes/Profile/index.tsx'),
    route(`reel`, 'routes/reel/layout.tsx', [
        index('routes/reel/index.tsx'),
        route(`:uniqueId`, 'routes/reel/dynamic/index.tsx')
    ]),
    route(`*`, 'routes/NotFound.tsx'),
] satisfies RouteConfig;
