root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server.exe ./"
bin = "./tmp/server.exe"
include_ext = ["go", "mod", "sum"]
exclude_dir = ["tmp", "vendor", "upload"]
delay = 200

[log]
time = true
